### ISSUE TITLE
Error: XKBNotFound

### ISSUE THREAD

**Issue by lukors** [maroider/winit_keyboard_tester#1]
I'm interested in testing this, but can't get it to run on Pop!_OS 20.10 (Ubuntu 20.10 based).

- Downloaded https://github.com/maroider/winit/tree/new-keyboard-linux
- Checked out `origin/new-keyboard-linux`
- Downloaded this repo next to it so the cargo path to the repo works.
- Do `cargo run`

The program doesn't start, I get the following in my terminal:

```text
     Running `target/debug/winit_keyboard_tester`
2021-05-08 21:32:25,689 TRACE [mio::poll] registering with poller
2021-05-08 21:32:25,689 TRACE [mio::poll] registering with poller
2021-05-08 21:32:25,690 TRACE [mio::poll] registering with poller
2021-05-08 21:32:25,690 TRACE [mio::poll] registering with poller
2021-05-08 21:32:25,690 TRACE [mio::poll] registering with poller
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: XKBNotFound', /home/lukas/Workspace/winit_keyboard_test/winit/src/platform_impl/linux/x11/mod.rs:235:18
```

**Comment by maroider** [comment]
You're probably missing `libxkbcommon`. Do you have the `libxkbcommon0` and `libxkbcommon-x11-0` packages installed?

**Comment by lukors** [comment]
Thanks for helping, looks like I have them:

```text
lukas@lukas-laptop:~$ sudo apt-get install libxkbcommon0 libxkbcommon-x11-0
[sudo] password for lukas: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxkbcommon-x11-0 is already the newest version (0.10.0-1).
libxkbcommon-x11-0 set to manually installed.
libxkbcommon0 is already the newest version (0.10.0-1).
libxkbcommon0 set to manually installed.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```

**Comment by maroider** [comment]
Well, that's unexpected. I'll see if I can look more into this tomorrow.

**Comment by maroider** [comment]
You may want to sprinkle some `dbg!();`s in [this function](https://github.com/maroider/winit/blob/bd03ac89e6a5cb4c4258b7960acb9bc2cbc857b4/src/platform_impl/linux/common/xkb_state.rs#L253-L281) to see where exactly the error is originating from.

**Comment by lukors** [comment]
Thanks for the pointer!

It's this line that errors: https://github.com/maroider/winit/blob/bd03ac89e6a5cb4c4258b7960acb9bc2cbc857b4/src/platform_impl/linux/common/xkb_state.rs#L262

And this is the line that leads to: https://github.com/maroider/xkbcommon-dl/blob/5307184c1c641d85bfe85f72c036a22a9261ef31/src/lib.rs#L306

Looks like I'm missing `libxkbcommon.so` somehow, despite the lib being installed? I know almost nothing about .so files. Let me know if there's something more I can do to help figure out the issue! :pray:

**Comment by maroider** [comment]
It seems like you've been affected by the issue addressed in [this PR](https://github.com/maroider/xkbcommon-dl/pull/1).

**Comment by lukors** [comment]
Yep, that did it! :D

I had to manually update the winit cargo file, so probably want to make sure that's updated before closing this issue.

Thanks!

EDIT:
It's working very well, looking forward to this landing!

Thanks a lot for doing this and nice work! :D

**Comment by maroider** [comment]
The `new-keyboard-linux` branch should point to the right commit now.
